#!/bin/bash

echo "Cleaning up..."
rm -rf \
	config.* \
	Makefile.in \
	aclocal* \
	compile \
	autom* \
	install-sh \
	depcomp \
	missing \
	test-driver \
	Makefile \
	stamp-h1 \
	netreg_tests* \
	libnetreg.a \
	test-suite.log \
	netreg_benchmarks*
