#!/bin/bash

echo "Cleaning up..."
rm -rf \
	config.* \
	Makefile.in \
	src/Makefile.in \
	aclocal* \
  compile \
	autom* \
	install-sh \
	depcomp \
	missing \
	test-driver \
  Makefile \
	src/libnetreg/config.h* \
  src/Makefile \
  src/.deps \
	src/stamp-h1 \
	src/libnetreg/Makefile.in \
  src/tests/.deps \
  src/tests/*.o \
  src/tests/.dirstamp \
  src/test-suite.log \
  src/test.log \
  src/test.trs \
  stamp-h1 \
  src/Makevars \
  src/libnetreg/Makefile \
  src/libnetreg/stamp-h1
 
find src -name *.a -delete
find src -name *.o -delete
find src -name *.dirstamp -delete
