// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// edgenet
Rcpp::List edgenet(SEXP XS, SEXP YS, SEXP GXS, SEXP GYS, const int n, const int p, const int q, const double lambda, const double psigx, const double psigy, const int niter, const double threshs, SEXP fs);
RcppExport SEXP netReg_edgenet(SEXP XSSEXP, SEXP YSSEXP, SEXP GXSSEXP, SEXP GYSSEXP, SEXP nSEXP, SEXP pSEXP, SEXP qSEXP, SEXP lambdaSEXP, SEXP psigxSEXP, SEXP psigySEXP, SEXP niterSEXP, SEXP threshsSEXP, SEXP fsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XS(XSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type YS(YSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type GXS(GXSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type GYS(GYSSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type psigx(psigxSEXP);
    Rcpp::traits::input_parameter< const double >::type psigy(psigySEXP);
    Rcpp::traits::input_parameter< const int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< const double >::type threshs(threshsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fs(fsSEXP);
    rcpp_result_gen = Rcpp::wrap(edgenet(XS, YS, GXS, GYS, n, p, q, lambda, psigx, psigy, niter, threshs, fs));
    return rcpp_result_gen;
END_RCPP
}
