// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/netReg.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// node_degrees_
std::vector<double> node_degrees_(const arma::Mat<double>& x);
static SEXP _netReg_node_degrees__try(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::Mat<double>& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(node_degrees_(x));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _netReg_node_degrees_(SEXP xSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_netReg_node_degrees__try(xSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// laplacian_
arma::Mat<double> laplacian_(const arma::Mat<double>& x);
static SEXP _netReg_laplacian__try(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::Mat<double>& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(laplacian_(x));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _netReg_laplacian_(SEXP xSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_netReg_laplacian__try(xSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// intercept_
arma::Col<double> intercept_(arma::Mat<double>& X, arma::Mat<double>& Y, arma::Mat<double>& B);
static SEXP _netReg_intercept__try(SEXP XSEXP, SEXP YSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::Mat<double>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::Mat<double>& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(intercept_(X, Y, B));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _netReg_intercept_(SEXP XSEXP, SEXP YSEXP, SEXP BSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_netReg_intercept__try(XSEXP, YSEXP, BSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _netReg_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("std::vector<double>(*node_degrees_)(const arma::Mat<double>&)");
        signatures.insert("arma::Mat<double>(*laplacian_)(const arma::Mat<double>&)");
        signatures.insert("arma::Col<double>(*intercept_)(arma::Mat<double>&,arma::Mat<double>&,arma::Mat<double>&)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _netReg_RcppExport_registerCCallable() { 
    R_RegisterCCallable("netReg", "_netReg_node_degrees_", (DL_FUNC)_netReg_node_degrees__try);
    R_RegisterCCallable("netReg", "_netReg_laplacian_", (DL_FUNC)_netReg_laplacian__try);
    R_RegisterCCallable("netReg", "_netReg_intercept_", (DL_FUNC)_netReg_intercept__try);
    R_RegisterCCallable("netReg", "_netReg_RcppExport_validate", (DL_FUNC)_netReg_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_netReg_node_degrees_", (DL_FUNC) &_netReg_node_degrees_, 1},
    {"_netReg_laplacian_", (DL_FUNC) &_netReg_laplacian_, 1},
    {"_netReg_intercept_", (DL_FUNC) &_netReg_intercept_, 3},
    {"_netReg_RcppExport_registerCCallable", (DL_FUNC) &_netReg_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_netReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
