# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edgenet <- function(XS, YS, GXS, GYS, n, p, q, lambda, psigx, psigy, niter, threshs, fs) {
    .Call('netReg_edgenet', PACKAGE = 'netReg', XS, YS, GXS, GYS, n, p, q, lambda, psigx, psigy, niter, threshs, fs)
}

