# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.edgenet.cpp <- function(XS, YS, GXS, GYS, n, p, q, lambda, psigx, psigy, n_iter, thresh, familys) {
    .Call('netReg_edgenet_rcpp_', PACKAGE = 'netReg', XS, YS, GXS, GYS, n, p, q, lambda, psigx, psigy, n_iter, thresh, familys)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('netReg_RcppExport_registerCCallable', PACKAGE = 'netReg')
})
